---
title: Group Activities
author: Brad Boehmke
layout: tutorial
permalink: /logm655_group_activities
---

Many data science projects cannot be completed by one person - especially if the project has a deadline. Thus, it's important that every analyst be able to work with other analysts in a team - and even with other teams of analysts. In this course students will exercise their teamwork skills by completing two in-class activities as described below. Teams must work with each other and must develop their method for working successfully within a group.

For both of these activities students will be separated into four teams - the number of students in each team will depend on the number of students registered for the course. Each team will address one of the following text mining goals:

- Topic modeling
- Parts of speech tagging
- Document summarization
- Named entity recognition

Student teams will be assigned to lead class discussions for both class meetings during one week of the quarter - the specific weeks are specified in the course syllabus. What the teams should during these class meetings is described below. My goal is to balance the number of students in each team - which means that some students may not be assigned to their prefereed topic.  However, preference will be given to students who can show that they are working on thesis projects related to one of these topic areas.

## Activity $\# 1$ Overview of Current Methods (20 pts):

During the first class meeting of their assigned week, teams will present a detailed overview of the current methods used to accomplish their chosen goal.  Teams should present the concept and mathematical theory behind several methods used to accomplish their chosen text mining goal.  Teams can use any publicly available resource, so long as they cite them in their presentation.  

__This activity is worth 20% of your overall course grade.__ Student grades for this activity will be graded based on (1) completion of the assignment, and (2) the degree to which each student contributed to the team in completing this activity. I will assign this value based a survey each student will fill out to describe the level of participation for each member of the team.  The survey will be used to distribute the grade appropriately as demonstrated by your effort towards assisting the group accomplish the assignment.  Survey scores will be based on a scale from 1 to 5, where a '5' means that the student was very involved in the effort and made important contributions a '1' means that a student was not involved and made few (if any) contributions.
	
## Activity #\# 2$ R Programming Tutorial (20 pts):

During the second class meeting of their assigned week, teams will give a tutorial on how to use the R programming language to implement the text mining methods and accomplish the goal.  There are a number of excellent resources to help with this project.

- [**Stack Overflow**](https://stackoverflow.com/search?q=natural+language+processing+R)
- [**CRAN Task View: Natural language Processing**](https://cran.r-project.org/web/views/NaturalLanguageProcessing.html)
- [**Github**](https://github.com/search?q=natural+language+processing)
- [**Kaggle Kernels**](https://www.kaggle.com/kernels)

Students will cite all sources from which they obtained any examples or data used in their tutorial and will clearly indicate which packages they used obtain their results. 

__This activity is worth 20% of your overall course grade.__ Student grades for this activity will be graded based on (1) completion of the assignment, and (2) the degree to which each student contributed to the team in completing this activity. I will assign this value based a survey each student will fill out to describe the level of participation for each member of the team.  The survey will be used to distribute the grade appropriately as demonstrated by your effort towards assisting the group accomplish the assignment.  Survey scores will be based on a scale from 1 to 5, where a '5' means that the student was very involved in the effort and made important contributions a '1' means that a student was not involved and made few (if any) contributions.