---
title: Term Project
date: Jason Freels
output: html_document
---

This course requires completion of an <u>individual</u> project that implements one or more of the the methods presented in the class.  The intent of the project is to apply one or multiple concepts learned within the class to an actual data set in order to perform knowledge discovery.  __The project must be approved by Maj Freels, NLT 19 October 2018.__  Students may use an application within their thesis project for work within this class.  The data set used for this project can be either pre-formatted text or something in textual form.  At a bare minimum, the text should include more than 5,000 words and should be in English.  While these requirements are minimums, the intent is that the problem is analyzed according to the concepts presented in this course and that the results are articulated in a clear manner. 
 
## Deliverables

This project is worth __60% of your total grade__ for this class.  You will provide two deliverables.

1. __Project IPR – Due Friday, 3 November (10 pts)__ -   This should be a focused 4-5 slide presentation (no more than 5 slides).  The goal of these slides is to describe what you are doing, why and where you are in your analysis.  You will not present this presentation; make sure the slides can speak for themselves (no use of notes in powerpoint – just the slides).  At a minimum, the slides should include the following:

- Title Slide
- Purpose 
    - What are you doing?
    -	Why?
-	Background
    -	Context into your analysis
    - Insight into your topic with rudimentary analysis
-	Interim Analysis
   -	Work not used in any other class previously
-	Discuss Next Steps

2. __Project Report – Due Friday, 8 December (50 pts)__ - For this part of the project assignment, provide a written report describing your analysis of your text and how it informs on the problem laid out in your project proposal.  Focus on insights, trends and analysis. This is where you are allowed to put the work you’ve done, but remember this document should flow.    This document (not including appendices) should be no longer than 20 pages (single spaced), with any charts/graphs relevant to the discussion imbedded and referenced in the body of the document.  Bulky or large figures or charts and examples of your code should be put into the appendix(cies).  The format of the report should have at least the following headings: 

- Abstract
- Problem Background (ending with a clear statement of the problem)
- Methodology (describe the data you used and your analysis)
- Findings and Conclusions (to include any future work)

Think of this report as something that could be read by a research sponsor.  All reports will be made available to the rest of the class (unless there are circumstances that might prevent this). 
